version: "3"
  

services:

  css:
    container_name: octothorpe
    build:
      context: ../octothorpe
      dockerfile: Dockerfile
    image: octothorpe
    volumes: 
      - style:/dist

  web:
    container_name: isar.desktop
    build:
      context: .
      dockerfile: Dockerfile.build
    image: isar.build
    depends_on:
      - css
    volumes:
      - style:/style
      - dist:/dist
    command: "ls -l style"

  host:
    image: nginx
    depends_on:
      - web
    volumes:
      - dist:/usr/share/nginx/html
    ports:
      - "80:80"
    command: "nginx -g 'daemon off;'"

volumes:
  dist:
  style: