version: "3"
  

services:

  web:
    container_name: isar.desktop.build
    build:
      context: .
      dockerfile: Dockerfile.build
    image: isar.build
    volumes:
      - dist:/dist

  host:
    image: nginx
    depends_on:
      - web
    volumes:
      - dist:/usr/share/nginx/html
    ports:
      - "80:80"
    command: "nginx -g 'daemon off;'"

volumes:
  dist: